name: path_icon
description: An icon widget based on a vector path.
version: 0.7.2
homepage: https://github.com/aloisdeniel/path_icon

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  xml: ^6.1.0
  path_drawing: ^1.0.1
  vector_math: ^2.1.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


